### ISSUE TITLE
Arguments on search

### ISSUE THREAD

**Issue by EL-R1** [Tajikarao/livechart.me-rest-api#1]
Hi !
Is it possible to add arguments for search endpoint such as `sort` which can be really useful (for me at least xD )

Maybe add same arguments as `season_chart` endpoint if it's possible.

```yaml
fields[]: next_episode,
category: tv | movies | ovas | all,
offset: 0,
sort: title | airdate | popularity | modified | countdown | anime.avg_rating,
titles: romaji | english,
leftovers: true | false,
hide_skipping: true | false
```
